project:
  type: book

book:
  title: "Validation of the Spiritual Harm and Abuse Scale (SHAS) with the Rating Scale Model"
  author:
    - Jack Huber, Gonzaga University
    - Dan Koch, Northwest University
  date: last-modified
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd
  downloads: [pdf, epub]
  page-navigation: true
  page-footer: 
    center: "Built in R with Quarto"
  navbar: 
    background: navy
    foreground: white
    right:
      - icon: house
        text: "Home"
        href: https://jackhuber.org
  site-url: https://spiritual-abuse.jackhuber.org

bibliography: [references.bib, packages.bib]
csl: apa.csl

format:
  html:
    theme: cosmo
  #pdf:
    #documentclass: article
    #keep-tex: true

editor: visual

