# Discussion {.unnumbered}

The purpose of this study was to further validate and enhance the Spiritual Harm and Abuse Scale (SHAS) with the use of the Rasch Rating Scale model. The present study improves upon the sample dependency of factor analysis results and contributes new understanding about the psychometric characteristics of the SHAS.

In this study, we examined unidimensionality, Rasch person/item separation reliability, model-data fit, distribution of the variable map based on the locations of persons and items, and individual item qualities of the SHAS. In terms of dimensionality, we found satisfactory evidence to unidimensionality to apply the Rasch Rating Scale model. We found the SHAS highly reliable using Rasch person/item separation reliability statistics, indicating that most of the items are sensitive enough to capture different levels of spiritual abuse and most persons' observed values overlap with the expected values. Similarly, there was close correspondence between the data and the Rasch Rating Scale model except for the outliers in the XXX ends of the continuum. This indicates reasonable model-data fit. Regarding the variable map, our results indicate that the SHAS, overall, captures a range of item severities that reflect the order structure of spiritual abuse. However, we also found a shortage of items at the very high and low ends of the continuum. The SHAS can capture people who have experienced moderate severity of spiritual abuse, but it is not sensitive enough to discriminate among people who have experienced very severe and less severe spiritual abuse. \\\[For example, based on our Rasch Rating scale model analysis, someone with a measure of − 3.00 logits and another with a measure of − 2.00 logits would be more likely to respond to the SHAS in the same way because there is no item on the scale that targets very low levels of spiritual abuse. Hence, we would not be able to detect which person has relatively more or less spiritual abuse in comparison to each other. It would be similarly impossible to distinguish levels of spiritual abuse between a person with a measure of 3.00 logits and another with a measure of 2.00 logits, and decide who has experienced more severe spiritual abuse due to lack of items at the high end of the continuum.\\\] Finally, in terms of item quality, XX of the XX items exhibited good psychometric quality, whereas XX items were misfits. XXX items were redundant because they provided the exact same information with identical pairs of each item, displaying the same contributions to the sensitivity of the SHAS. Hence, they can be removed from the scale to shorten the duration of administration.

Use of the Rasch measurement model in our study provided a powerful analysis of the functioning of the SHAS at the item level and offered in-depth insights on applicability of the scale in wider contexts due to its sample independent nature. Whereas factor analytic approaches such as exploratory factor analysis and confirmatory factor analysis do not provide invariant measurement due to their sample dependency, the Rasch measurement model is independent from the items that form the scale and independent from the sample that the scale is administered to. This feature will increase the applicability of the scale in wider contexts and replicability of the present study in different populations due to the possibility of direct application of the standards developed in one study to data administered in another study (Yan and Mok 2012).

In conclusion, the results of this study provide strong evidence for the validation of the SHAS despite the need for considering the deletion of XX items that are misfits and of XX items that are redundant. The revision or development of new items can also be considered to capture gradations of challenges at the very high and low ends of the continuum to detect people with very high and low levels of spiritual abuse.

## Implications and future directions

This study presents the validation of the SHAS using the Rasch measurement model, for assessing spiritual abuse in adults. The findings have important implications for clinicians and researchers who are concerned about spiritual abuse. The finding that the majority of the SHAS items were of high quality implies that the items provide adequate information to measure moderate levels of spiritual abuse. However, we found the SHAS less able to distinguish people with very high and low levels of spiritual abuse. Hence, for now clinicians and researchers should be cautious when interpreting their results for people who have very high and low spiritual abuse levels.

We echo the same limitations of these data noted in \@KochEdstrom2022. The SHAS was developed on a largely white and Protestant/former Protestant population. Possibly major types or sub-themes of spiritual abuse not captured here are more prominent in other religious traditions. This would be a fruitful area of future study. Research into spiritual abuse among the LGBTQ+ community might also yield insights specific to that population. Future research could also distinguish normed scores of this scale for different populations and denominations.

The final screener has the potential to both improve therapy for innumerable clients who have experienced negative religious experiences and to contribute a knowledge base for any future clinical training around working with spiritually abused clients. The scale may also contribute to future research that could be critical in understanding not only the mechanisms and experience of spiritual abuse but also perhaps the enduring power of religion, both to heal and to harm.

# Data Availability

Data will be made available in accordance with xxx. Within one year of publication of manuscripts addressing the aims of the grant, investigators will make a deidentified, anonymized dataset available to the public.

# Code Availability

Code for the analyses presented in this paper will be made available upon request.

# Acknowledgments

This manuscript was not supported by grant funding. The views expressed in this article are those of the authors and do not necessarily reflect the position or policy of the Swedish Medical Center or Northwest University.

# Funding

This research was not supported by grant funding.

# Author Information

## Affiliations

**Department of Pharmacy, Swedish Medical Center, Seattle, USA**

Jack Huber

**Department of Psychology, Northwest University, Kirkland, USA**

Dan Koch

## Corresponding Author

Correspondence to [Jack Huber](mailto:jack.bernard.huber@gmail.com).

# Ethics Declarations

## Conflict of Interest

The authors declare no conflict of interest.
