# Introduction {.unnumbered}

Spiritual and religious abuse has been a serious problem which is gaining the attention of the psychological research community.

Research to date has attempted to define spiritual abuse. Spiritual abuse can include a wide range of psychologically controlling behaviors. It can include diverse emotionally abusive behaviors such as rejecting, isolating, terrorizing, ignoring, corrupting, verbally assaulting, and over-pressuring [@Pearl-1994]. It can include sexual or other physical forms of abuse by a clergy member [@Doyle-2006]. Spiritual abuse may include theologically sanctioned mistreatment of a group of people such LGBTQ+ persons [@Foster-2015]. Spiritual abuse can range in specificity from abusive acts by religious leaders to abuse perpetrated by a religious group or person representing a religious group with a religious or spiritual component [@Swindle-2017]. Spiritual abuse can also include quoting scripture or invoking divine rationale for mistreatment [@Oakley-2018]. @KochEdstrom2022 define spiritual abuse broadly as "a type of emotional and psychological abuse perpetrated by a religious leader or group and/or with a religious or spiritual component, usually involving coercion or control."

Spiritual and religious abuse has serious negative effects [@Ward-2011; @Swindle-2017; @Oakley-2014; @Stevens-2019]. Spiritual and religious abuse can be traumatic, and such trauma that occurs in a religious or spiritual setting may deprive victims of religion and spirituality as a coping strategy. Religious leaders may be on a par with parents in their potential for abusive harm. There are also concerns related to secondary trauma for clinicians working with R/S abused clients [@Gubi-2009].

In light of these concerns, a valid scale of spiritual harm and abuse is needed. Practitioners who treat clients who may be victims of religious and spiritual abuse need an instrument to assess the extent and severity of spiritual abuse suffered by a client. Researchers need a reliable measurement of spiritual abuse to examine relationships between spiritual abuse and any number of other psychological, health, or other measures.

One promising instrument is the nascent Spiritual Harm & Abuse Scale (SHAS) [@KochEdstrom2022]. These authors drew from a recent unpublished scale of religious and spiritual abuse [@Keller2016], other scales of abuse [@Kira-2008; @Sanders-1995; @Carlson-2011; @Briere-1989], and interviews with victims of abuse to document a wide range of experiences and emotional states that could be described as spiritual harm and abuse. From this work they developed a pool of 66 prompts for an online community survey which they fielded in 2021. Exploratory factor analysis of the data revealed six factors which the authors used to distill the instrument to a 27-item scale with six subscales.

In this paper, we further validate the SHAS by using item response theory. Item response theory can enhance clinical assessments in several ways. First, IRT provides interval-level measures which are more appropriate for statistical analysis than ordinal-level sum scores and factor scores. Second, IRT provides one scale along which both items and persons can be located. Third, measurements derived from IRT are sample-free. This means it is possible to estimate a person's level of the latent construct free of the distribution of individual items and to estimate an item's difficulty level free from the distribution of people used in the sample. Finally, IRT improves upon single overall reliability coefficients like Cronbach's alpha by providing examination of precision across the score continuum.

The goal of this study was thus to use the Rating Scale Model [@Andrich1978] to validate the SHAS in several ways. First, we aimed to express the SHAS as a single interval-level outcome measure of cumulative lifetime severity of spiritual harm and abuse. Second, we aimed to enrich the diagnostic value of the items and scale by examining severity. Third, we aimed to examine the distribution of item severities to see where the scale provides the most precise, reliable measurement of spiritual abuse. Such a scale also lays the foundation to further develop the SHAS by identifying anchor items that can calibrate with pilot items on future forms. Finally, we aimed to establish a SHAS score that is free of differential item functioning based on race, gender, and other demographic variables.
