<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Validation of the Spiritual Harm and Abuse Scale with the Rating Scale Model - Results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./discussion.html" rel="next">
<link href="./methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Validation of the Spiritual Harm and Abuse Scale with the Rating Scale Model</span>
  </a>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Results</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Abstract</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">Introduction</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./methods.html" class="sidebar-item-text sidebar-link">Methods</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./results.html" class="sidebar-item-text sidebar-link active">Results</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./discussion.html" class="sidebar-item-text sidebar-link">Discussion</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#participant-characteristics" id="toc-participant-characteristics" class="nav-link active" data-scroll-target="#participant-characteristics">Participant Characteristics</a></li>
  <li><a href="#initial-item-analysis" id="toc-initial-item-analysis" class="nav-link" data-scroll-target="#initial-item-analysis">Initial Item Analysis</a></li>
  <li><a href="#unidimensionality-and-local-independence" id="toc-unidimensionality-and-local-independence" class="nav-link" data-scroll-target="#unidimensionality-and-local-independence">Unidimensionality and Local Independence</a>
  <ul class="collapse">
  <li><a href="#principal-components" id="toc-principal-components" class="nav-link" data-scroll-target="#principal-components">Principal Components</a></li>
  <li><a href="#proportion-of-variance" id="toc-proportion-of-variance" class="nav-link" data-scroll-target="#proportion-of-variance">Proportion of Variance</a></li>
  <li><a href="#principal-component-analysis-of-residuals-pcar" id="toc-principal-component-analysis-of-residuals-pcar" class="nav-link" data-scroll-target="#principal-component-analysis-of-residuals-pcar">Principal Component Analysis of Residuals (PCAR)</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  </ul></li>
  <li><a href="#rasch-rating-scale-analysis" id="toc-rasch-rating-scale-analysis" class="nav-link" data-scroll-target="#rasch-rating-scale-analysis">Rasch Rating Scale Analysis</a>
  <ul class="collapse">
  <li><a href="#item-severity-parameters-and-fit-statistics" id="toc-item-severity-parameters-and-fit-statistics" class="nav-link" data-scroll-target="#item-severity-parameters-and-fit-statistics">Item Severity Parameters and Fit Statistics</a></li>
  <li><a href="#reliability" id="toc-reliability" class="nav-link" data-scroll-target="#reliability">Reliability</a></li>
  <li><a href="#item-person-map" id="toc-item-person-map" class="nav-link" data-scroll-target="#item-person-map">Item-Person Map</a></li>
  <li><a href="#model-data-fit" id="toc-model-data-fit" class="nav-link" data-scroll-target="#model-data-fit">Model-Data Fit</a></li>
  </ul></li>
  <li><a href="#dif-analysis" id="toc-dif-analysis" class="nav-link" data-scroll-target="#dif-analysis">DIF Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Results</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="participant-characteristics" class="level2">
<h2 class="anchored" data-anchor-id="participant-characteristics">Participant Characteristics</h2>
<p>In total, 3,222 individuals responded to the survey. Participants who did not opt out and completed at least 50% of the spiritual abuse item pool were considered complete responders and included in the study (N = 3,219). Non-responders included those who responded to less than half of the items (N=3).</p>
<p>Most of the participants responded to the demographics items, and we present the results of these items in <a href="#tbl-DemsTable">Table&nbsp;<span>1</span></a>. Most of the sample (76%) was adults between the ages of 25 and 56, with Millennials (Ages 25-40) comprising nearly 56% of the sample, followed by Generation X (Ages 41-56) comprising 21%. Half the sample was cisgender female (51%) and 41% was cisgender male. The sample was also predominantly white (87%) and straight (82%).</p>
<div class="cell" data-verbose="false">
<div class="cell-output-display">
<div id="tbl-DemsTable" class="anchored">

<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;"><caption>Table 1:  Demographic Characteristics </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Characteristic </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> % </th>
  </tr>
 </thead>
<tbody>
  <tr grouplength="7"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Generation</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Millennial (Ages 25-40) </td>
   <td style="text-align:right;"> 1,793 </td>
   <td style="text-align:right;"> 55.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Generation X (Ages 41-56) </td>
   <td style="text-align:right;"> 677 </td>
   <td style="text-align:right;"> 21.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Baby Boom (Ages 57-76) </td>
   <td style="text-align:right;"> 326 </td>
   <td style="text-align:right;"> 10.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Gen Z (Below Age 25) </td>
   <td style="text-align:right;"> 250 </td>
   <td style="text-align:right;"> 7.8 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Silent Generation (Age 77+) </td>
   <td style="text-align:right;"> 166 </td>
   <td style="text-align:right;"> 5.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 10 </td>
   <td style="text-align:right;"> 0.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
  <tr grouplength="8"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Gender</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Cisgender Female </td>
   <td style="text-align:right;"> 1,635 </td>
   <td style="text-align:right;"> 50.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Cisgender Male </td>
   <td style="text-align:right;"> 1,320 </td>
   <td style="text-align:right;"> 41.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 162 </td>
   <td style="text-align:right;"> 5.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Other </td>
   <td style="text-align:right;"> 49 </td>
   <td style="text-align:right;"> 1.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Prefer not to say </td>
   <td style="text-align:right;"> 36 </td>
   <td style="text-align:right;"> 1.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Transgender Female </td>
   <td style="text-align:right;"> 12 </td>
   <td style="text-align:right;"> 0.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Transgender Male </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 0.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
  <tr grouplength="9"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Race</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> White/European American </td>
   <td style="text-align:right;"> 2,786 </td>
   <td style="text-align:right;"> 86.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 162 </td>
   <td style="text-align:right;"> 5.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Other </td>
   <td style="text-align:right;"> 92 </td>
   <td style="text-align:right;"> 2.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Ethnically of Hispanic/Latin origin </td>
   <td style="text-align:right;"> 73 </td>
   <td style="text-align:right;"> 2.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Black/African American </td>
   <td style="text-align:right;"> 51 </td>
   <td style="text-align:right;"> 1.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Asian </td>
   <td style="text-align:right;"> 47 </td>
   <td style="text-align:right;"> 1.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> American Indian / Alaska Native </td>
   <td style="text-align:right;"> 7 </td>
   <td style="text-align:right;"> 0.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Native Hawai'ian / Pacific Islander </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
  <tr grouplength="8"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Sexual Orientation</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Straight </td>
   <td style="text-align:right;"> 2,626 </td>
   <td style="text-align:right;"> 81.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Bisexual </td>
   <td style="text-align:right;"> 174 </td>
   <td style="text-align:right;"> 5.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 158 </td>
   <td style="text-align:right;"> 4.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Gay/Lesbian </td>
   <td style="text-align:right;"> 102 </td>
   <td style="text-align:right;"> 3.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Queer </td>
   <td style="text-align:right;"> 67 </td>
   <td style="text-align:right;"> 2.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Don't know </td>
   <td style="text-align:right;"> 51 </td>
   <td style="text-align:right;"> 1.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Asexual </td>
   <td style="text-align:right;"> 44 </td>
   <td style="text-align:right;"> 1.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The survey also included several items asking participants about their religious background and current identification and beliefs. We report the results of these religious characteristics in <a href="#tbl-ChristTable">Table&nbsp;<span>2</span></a>. Most of the sample (87%) was raised in a Christian home. Over half (56%) now self-identify as Protestant, followed by a quarter who do not identify with a religious tradition (16% “Nothing in particular” and 10% “Agnostic”). Over 60% view the Bible as divinely inspired if not to be interpreted literally.</p>
<div class="cell" data-verbose="false">
<div class="cell-output-display">
<div id="tbl-ChristTable" class="anchored">

<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;"><caption>Table 2:  Religious Characteristics </caption>
 <thead>
  <tr>
   <th style="text-align:left;"> Characteristic </th>
   <th style="text-align:right;"> N </th>
   <th style="text-align:right;"> % </th>
  </tr>
 </thead>
<tbody>
  <tr grouplength="4"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Raised in a Christian home</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Yes </td>
   <td style="text-align:right;"> 2,795 </td>
   <td style="text-align:right;"> 86.7 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> No </td>
   <td style="text-align:right;"> 266 </td>
   <td style="text-align:right;"> 8.3 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 161 </td>
   <td style="text-align:right;"> 5.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
  <tr grouplength="10"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Current Religious Identification</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Protestant </td>
   <td style="text-align:right;"> 1,833 </td>
   <td style="text-align:right;"> 56.9 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Nothing in particular </td>
   <td style="text-align:right;"> 518 </td>
   <td style="text-align:right;"> 16.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Agnostic </td>
   <td style="text-align:right;"> 325 </td>
   <td style="text-align:right;"> 10.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 165 </td>
   <td style="text-align:right;"> 5.1 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Atheist </td>
   <td style="text-align:right;"> 128 </td>
   <td style="text-align:right;"> 4.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Orthodox Christian </td>
   <td style="text-align:right;"> 79 </td>
   <td style="text-align:right;"> 2.5 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Catholic </td>
   <td style="text-align:right;"> 66 </td>
   <td style="text-align:right;"> 2.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Mormon </td>
   <td style="text-align:right;"> 57 </td>
   <td style="text-align:right;"> 1.8 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Other religious tradition </td>
   <td style="text-align:right;"> 51 </td>
   <td style="text-align:right;"> 1.6 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
  <tr grouplength="5"><td colspan="3" style="border-bottom: 1px solid #00000020;"><strong>Current View of the Bible</strong></td></tr>
<tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> The Bible is the inspired word of God but not everything should be taken literally, word for word </td>
   <td style="text-align:right;"> 2,010 </td>
   <td style="text-align:right;"> 62.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> The Bible is an ancient book of fables, legends, history and moral precepts recorded by man </td>
   <td style="text-align:right;"> 870 </td>
   <td style="text-align:right;"> 27.0 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> The Bible is the actual word of God and is to be taken literally, word for word </td>
   <td style="text-align:right;"> 174 </td>
   <td style="text-align:right;"> 5.4 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> NA </td>
   <td style="text-align:right;"> 168 </td>
   <td style="text-align:right;"> 5.2 </td>
  </tr>
  <tr>
   <td style="text-align:left;padding-left: 2em;" indentlevel="1"> Total </td>
   <td style="text-align:right;"> 3,222 </td>
   <td style="text-align:right;"> 100.0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<p><a href="#fig-theology">Figure&nbsp;<span>1</span></a> depicts the results of the item asking participants their current theological identification. According this plot, most of the sample are moderate in their theological views. Very few report being “Very Liberal” or “Very Conservative”.</p>
<div class="cell fig-cap-location-top" data-layout-align="left" data-verbose="false">
<div class="cell-output-display">
<div id="fig-theology" class="quarto-figure quarto-figure-left anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-theology-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 1: Current Theological Identification</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="initial-item-analysis" class="level2">
<h2 class="anchored" data-anchor-id="initial-item-analysis">Initial Item Analysis</h2>
<p>In <a href="#tbl-ClassicalItemTable">Table&nbsp;<span>3</span></a> we report classical statistics for the 66 SHAS items. We sorted the items by their mean. We flagged six items due to extreme values of skew (less than -2 or greater than +2) or kurtosis (less than -7 or greater than +7) and item-total correlations below 0.50. These included items EQ17, EQ27, EQ41, EQ46, EQ55, and EQ60. Category response proportions show that most people responded “Never” to these items. Thus, because these items do not apply to the vast majority of people in this population, we removed them from the item pool. This reduced the pool from 66 to 59 items.</p>
<div class="cell" data-verbose="false">
<div class="cell-output-display">
<div id="tbl-ClassicalItemTable" class="anchored">

<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;"><caption>Table 3:  Classical Item Statistics </caption>
 <thead>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> 1 </th>
   <th style="text-align:right;"> 2 </th>
   <th style="text-align:right;"> 3 </th>
   <th style="text-align:right;"> 4 </th>
   <th style="text-align:right;"> 5 </th>
   <th style="text-align:right;"> n </th>
   <th style="text-align:right;"> mean </th>
   <th style="text-align:right;"> sd </th>
   <th style="text-align:right;"> skew </th>
   <th style="text-align:right;"> kurtosis </th>
   <th style="text-align:right;"> Item-total correlation </th>
   <th style="text-align:left;"> flag </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> EQ46 - Treated as less than because of my skin color </td>
   <td style="text-align:right;"> 0.94 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.01 </td>
   <td style="text-align:right;"> 0.00 </td>
   <td style="text-align:right;"> 3,211 </td>
   <td style="text-align:right;"> 1.11 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 5.15 </td>
   <td style="text-align:right;"> 28.93 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ41 - Denied opportunities to serve because of my sexual orientation </td>
   <td style="text-align:right;"> 0.89 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 3,211 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 0.88 </td>
   <td style="text-align:right;"> 3.30 </td>
   <td style="text-align:right;"> 9.87 </td>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ17 - Treated as less than b/c my sexual orientation </td>
   <td style="text-align:right;"> 0.88 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 3,208 </td>
   <td style="text-align:right;"> 1.34 </td>
   <td style="text-align:right;"> 0.97 </td>
   <td style="text-align:right;"> 2.87 </td>
   <td style="text-align:right;"> 6.96 </td>
   <td style="text-align:right;"> 0.35 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ47 - Medical care being postponed/withheld for religious reasons </td>
   <td style="text-align:right;"> 0.70 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.01 </td>
   <td style="text-align:right;"> 3,218 </td>
   <td style="text-align:right;"> 1.48 </td>
   <td style="text-align:right;"> 0.86 </td>
   <td style="text-align:right;"> 1.93 </td>
   <td style="text-align:right;"> 3.40 </td>
   <td style="text-align:right;"> 0.52 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ60 - Encouraged by leader to stay in abusive marriage </td>
   <td style="text-align:right;"> 0.76 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 3,214 </td>
   <td style="text-align:right;"> 1.49 </td>
   <td style="text-align:right;"> 0.99 </td>
   <td style="text-align:right;"> 2.05 </td>
   <td style="text-align:right;"> 3.22 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ55 - Hearing cultural references in sermons unfamiliar to my race/eth. subculture </td>
   <td style="text-align:right;"> 0.66 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 3,205 </td>
   <td style="text-align:right;"> 1.58 </td>
   <td style="text-align:right;"> 0.95 </td>
   <td style="text-align:right;"> 1.66 </td>
   <td style="text-align:right;"> 2.12 </td>
   <td style="text-align:right;"> 0.28 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ72 - Feeling as if God harmed me directly </td>
   <td style="text-align:right;"> 0.64 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 3,070 </td>
   <td style="text-align:right;"> 1.64 </td>
   <td style="text-align:right;"> 0.99 </td>
   <td style="text-align:right;"> 1.52 </td>
   <td style="text-align:right;"> 1.55 </td>
   <td style="text-align:right;"> 0.54 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ81 - Nightmares about my negative religious experiences </td>
   <td style="text-align:right;"> 0.56 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.06 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 3,073 </td>
   <td style="text-align:right;"> 1.77 </td>
   <td style="text-align:right;"> 1.04 </td>
   <td style="text-align:right;"> 1.23 </td>
   <td style="text-align:right;"> 0.66 </td>
   <td style="text-align:right;"> 0.65 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ65 - Cut off/shunned by more religious family members </td>
   <td style="text-align:right;"> 0.59 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 1.82 </td>
   <td style="text-align:right;"> 1.18 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.61 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ10 - Asked to give up personal goals by pastor </td>
   <td style="text-align:right;"> 0.59 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 1.83 </td>
   <td style="text-align:right;"> 1.18 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.64 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ26 - Pressured to forgive abuser while abuse was ongoing </td>
   <td style="text-align:right;"> 0.60 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.06 </td>
   <td style="text-align:right;"> 3,212 </td>
   <td style="text-align:right;"> 1.87 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 1.24 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.66 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ24 - Expected to consult pastor/leader before making non-religious decisions </td>
   <td style="text-align:right;"> 0.56 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 3,221 </td>
   <td style="text-align:right;"> 1.89 </td>
   <td style="text-align:right;"> 1.18 </td>
   <td style="text-align:right;"> 1.10 </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 0.66 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ23 - Prayer replacing needed medical interventions </td>
   <td style="text-align:right;"> 0.51 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 0.03 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 1.92 </td>
   <td style="text-align:right;"> 1.13 </td>
   <td style="text-align:right;"> 1.02 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.64 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ27 - Denied opportunities to serve b/c of my gender </td>
   <td style="text-align:right;"> 0.60 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 1.94 </td>
   <td style="text-align:right;"> 1.35 </td>
   <td style="text-align:right;"> 1.14 </td>
   <td style="text-align:right;"> -0.13 </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:left;"> * </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ31 - Shunned/ignored by pastor/church/group </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.03 </td>
   <td style="text-align:right;"> 1.19 </td>
   <td style="text-align:right;"> 0.92 </td>
   <td style="text-align:right;"> -0.20 </td>
   <td style="text-align:right;"> 0.64 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ30 - Deterred from seeking mental health treatment/counseling/medication </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.04 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 0.88 </td>
   <td style="text-align:right;"> -0.46 </td>
   <td style="text-align:right;"> 0.70 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ43 - Shamed by pastor/group for poor spiritual/moral performance </td>
   <td style="text-align:right;"> 0.46 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 0.04 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.04 </td>
   <td style="text-align:right;"> 1.18 </td>
   <td style="text-align:right;"> 0.86 </td>
   <td style="text-align:right;"> -0.31 </td>
   <td style="text-align:right;"> 0.73 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ68 - Anxiety attacks triggered by religious stimuli </td>
   <td style="text-align:right;"> 0.49 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,073 </td>
   <td style="text-align:right;"> 2.06 </td>
   <td style="text-align:right;"> 1.23 </td>
   <td style="text-align:right;"> 0.83 </td>
   <td style="text-align:right;"> -0.51 </td>
   <td style="text-align:right;"> 0.68 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ52 - Blamed for harm I suffered rather than blaming who harmed me </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.08 </td>
   <td style="text-align:right;"> 1.26 </td>
   <td style="text-align:right;"> 0.85 </td>
   <td style="text-align:right;"> -0.52 </td>
   <td style="text-align:right;"> 0.76 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ70 - Feeling betrayed by God </td>
   <td style="text-align:right;"> 0.42 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,069 </td>
   <td style="text-align:right;"> 2.11 </td>
   <td style="text-align:right;"> 1.18 </td>
   <td style="text-align:right;"> 0.79 </td>
   <td style="text-align:right;"> -0.36 </td>
   <td style="text-align:right;"> 0.56 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ49 - Leadership/group protecting and elevating abusive individuals </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,213 </td>
   <td style="text-align:right;"> 2.12 </td>
   <td style="text-align:right;"> 1.23 </td>
   <td style="text-align:right;"> 0.79 </td>
   <td style="text-align:right;"> -0.50 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ16 - Church/community abandoning me in difficult time </td>
   <td style="text-align:right;"> 0.45 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.06 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.13 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 0.83 </td>
   <td style="text-align:right;"> -0.50 </td>
   <td style="text-align:right;"> 0.69 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ57 - Developing mental/physical ailments from conforming to group/leader’s expectation </td>
   <td style="text-align:right;"> 0.48 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.15 </td>
   <td style="text-align:right;"> 1.33 </td>
   <td style="text-align:right;"> 0.78 </td>
   <td style="text-align:right;"> -0.70 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ20 - Members pressured to give money despite financial hardship </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.16 </td>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> 0.82 </td>
   <td style="text-align:right;"> -0.71 </td>
   <td style="text-align:right;"> 0.68 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ62 - Scripture used to justify physical violence </td>
   <td style="text-align:right;"> 0.43 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 2.16 </td>
   <td style="text-align:right;"> 1.24 </td>
   <td style="text-align:right;"> 0.69 </td>
   <td style="text-align:right;"> -0.67 </td>
   <td style="text-align:right;"> 0.65 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ59 - Pastor/group blame victim for their abuse </td>
   <td style="text-align:right;"> 0.42 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.16 </td>
   <td style="text-align:right;"> 1.23 </td>
   <td style="text-align:right;"> 0.70 </td>
   <td style="text-align:right;"> -0.65 </td>
   <td style="text-align:right;"> 0.76 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ21 - Taught I would risk Hell if left my church/group </td>
   <td style="text-align:right;"> 0.51 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 3,218 </td>
   <td style="text-align:right;"> 2.20 </td>
   <td style="text-align:right;"> 1.47 </td>
   <td style="text-align:right;"> 0.81 </td>
   <td style="text-align:right;"> -0.83 </td>
   <td style="text-align:right;"> 0.69 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ50 - Treated as less than because of my gender </td>
   <td style="text-align:right;"> 0.52 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.23 </td>
   <td style="text-align:right;"> 1.47 </td>
   <td style="text-align:right;"> 0.70 </td>
   <td style="text-align:right;"> -1.04 </td>
   <td style="text-align:right;"> 0.54 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ82 - Having trouble navigating life outside my church/community </td>
   <td style="text-align:right;"> 0.38 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 3,071 </td>
   <td style="text-align:right;"> 2.24 </td>
   <td style="text-align:right;"> 1.21 </td>
   <td style="text-align:right;"> 0.62 </td>
   <td style="text-align:right;"> -0.62 </td>
   <td style="text-align:right;"> 0.61 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ64 - Witnessing women pressured to stay in unfaithful/abusive marriages </td>
   <td style="text-align:right;"> 0.39 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 2.26 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 0.67 </td>
   <td style="text-align:right;"> -0.70 </td>
   <td style="text-align:right;"> 0.71 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ28 - Leadershi/group protecting abusive individuals </td>
   <td style="text-align:right;"> 0.37 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.06 </td>
   <td style="text-align:right;"> 3,216 </td>
   <td style="text-align:right;"> 2.26 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 0.63 </td>
   <td style="text-align:right;"> -0.73 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ40 - Threatening Divine punishment to keep group members in line </td>
   <td style="text-align:right;"> 0.44 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 2.28 </td>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> 0.67 </td>
   <td style="text-align:right;"> -0.88 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ63 - Shamed by pastor/group for raising questions or concerns </td>
   <td style="text-align:right;"> 0.36 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.06 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.30 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 0.58 </td>
   <td style="text-align:right;"> -0.77 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ19 - Behavior excessively monitored by pastor/group </td>
   <td style="text-align:right;"> 0.40 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.32 </td>
   <td style="text-align:right;"> 1.33 </td>
   <td style="text-align:right;"> 0.56 </td>
   <td style="text-align:right;"> -0.96 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ51 - Extreme pressure to be pastor/missionary/spiritual leader </td>
   <td style="text-align:right;"> 0.41 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 3,216 </td>
   <td style="text-align:right;"> 2.33 </td>
   <td style="text-align:right;"> 1.38 </td>
   <td style="text-align:right;"> 0.59 </td>
   <td style="text-align:right;"> -0.98 </td>
   <td style="text-align:right;"> 0.62 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ53 - Scripture used to justify abusive parent-child behavior </td>
   <td style="text-align:right;"> 0.39 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 3,218 </td>
   <td style="text-align:right;"> 2.36 </td>
   <td style="text-align:right;"> 1.35 </td>
   <td style="text-align:right;"> 0.55 </td>
   <td style="text-align:right;"> -0.97 </td>
   <td style="text-align:right;"> 0.73 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ79 - Distrust of God </td>
   <td style="text-align:right;"> 0.33 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 3,068 </td>
   <td style="text-align:right;"> 2.40 </td>
   <td style="text-align:right;"> 1.27 </td>
   <td style="text-align:right;"> 0.50 </td>
   <td style="text-align:right;"> -0.81 </td>
   <td style="text-align:right;"> 0.61 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ34 - Scripture used to justify physical punishment/severe discipline </td>
   <td style="text-align:right;"> 0.34 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.46 </td>
   <td style="text-align:right;"> 1.33 </td>
   <td style="text-align:right;"> 0.42 </td>
   <td style="text-align:right;"> -1.05 </td>
   <td style="text-align:right;"> 0.65 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ29 - Feeling special when in pastor’s good graces; otherwise ignored </td>
   <td style="text-align:right;"> 0.34 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 3,213 </td>
   <td style="text-align:right;"> 2.47 </td>
   <td style="text-align:right;"> 1.34 </td>
   <td style="text-align:right;"> 0.40 </td>
   <td style="text-align:right;"> -1.08 </td>
   <td style="text-align:right;"> 0.69 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ73 - Self-hatred or self-loathing </td>
   <td style="text-align:right;"> 0.31 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.09 </td>
   <td style="text-align:right;"> 3,072 </td>
   <td style="text-align:right;"> 2.50 </td>
   <td style="text-align:right;"> 1.31 </td>
   <td style="text-align:right;"> 0.38 </td>
   <td style="text-align:right;"> -1.00 </td>
   <td style="text-align:right;"> 0.64 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ11 - Disagree w/pastor portrayed as evil </td>
   <td style="text-align:right;"> 0.32 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 3,216 </td>
   <td style="text-align:right;"> 2.52 </td>
   <td style="text-align:right;"> 1.35 </td>
   <td style="text-align:right;"> 0.38 </td>
   <td style="text-align:right;"> -1.12 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ58 - Terror/horror used to motivate religious decisions </td>
   <td style="text-align:right;"> 0.32 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 2.53 </td>
   <td style="text-align:right;"> 1.34 </td>
   <td style="text-align:right;"> 0.34 </td>
   <td style="text-align:right;"> -1.09 </td>
   <td style="text-align:right;"> 0.73 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ7 - Pastor speaking on God's behalf </td>
   <td style="text-align:right;"> 0.35 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 3,215 </td>
   <td style="text-align:right;"> 2.54 </td>
   <td style="text-align:right;"> 1.43 </td>
   <td style="text-align:right;"> 0.39 </td>
   <td style="text-align:right;"> -1.21 </td>
   <td style="text-align:right;"> 0.67 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ42 - Seeing others shamed/shunned by pastor/leader/group </td>
   <td style="text-align:right;"> 0.25 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.26 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.08 </td>
   <td style="text-align:right;"> 3,215 </td>
   <td style="text-align:right;"> 2.60 </td>
   <td style="text-align:right;"> 1.25 </td>
   <td style="text-align:right;"> 0.28 </td>
   <td style="text-align:right;"> -0.96 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ44 - Love/acceptance offered only for high spiritual/moral performance </td>
   <td style="text-align:right;"> 0.30 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.61 </td>
   <td style="text-align:right;"> 1.35 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> -1.20 </td>
   <td style="text-align:right;"> 0.80 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ56 - Being made to feel I was crazy/weird for doubts/questions </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.72 </td>
   <td style="text-align:right;"> 1.37 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> -1.24 </td>
   <td style="text-align:right;"> 0.82 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ18 - Church/pastor discourage critical thinking </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 3,220 </td>
   <td style="text-align:right;"> 2.75 </td>
   <td style="text-align:right;"> 1.37 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> -1.21 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ45 - Developmentally-inappropriate/anxious Hell/Satan/demons taught to young children </td>
   <td style="text-align:right;"> 0.29 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.76 </td>
   <td style="text-align:right;"> 1.45 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> -1.33 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ78 - A lack of self-worth </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 3,071 </td>
   <td style="text-align:right;"> 2.77 </td>
   <td style="text-align:right;"> 1.30 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> -1.09 </td>
   <td style="text-align:right;"> 0.67 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ36 - Mental/physical problems interpreted as spiritual/moral weakness </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 3,216 </td>
   <td style="text-align:right;"> 2.78 </td>
   <td style="text-align:right;"> 1.34 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> -1.17 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ61 - Developmentally-inappropriate/anxious end times descriptions taught to young children </td>
   <td style="text-align:right;"> 0.30 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.78 </td>
   <td style="text-align:right;"> 1.47 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> -1.37 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ32 - Feeling unable to express unhappiness </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 2.79 </td>
   <td style="text-align:right;"> 1.32 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> -1.14 </td>
   <td style="text-align:right;"> 0.73 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ74 - Sadness over the loss of my faith/religious community </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 3,071 </td>
   <td style="text-align:right;"> 2.79 </td>
   <td style="text-align:right;"> 1.29 </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> -1.08 </td>
   <td style="text-align:right;"> 0.60 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ76 - Feeling I wasted years of my life in a church/set of beliefs </td>
   <td style="text-align:right;"> 0.28 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 3,072 </td>
   <td style="text-align:right;"> 2.83 </td>
   <td style="text-align:right;"> 1.48 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> -1.39 </td>
   <td style="text-align:right;"> 0.74 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ54 - Being explicitly taught to distrust my intuitions </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.92 </td>
   <td style="text-align:right;"> 1.40 </td>
   <td style="text-align:right;"> 0.01 </td>
   <td style="text-align:right;"> -1.26 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ37 - Made to feel less spiritually mature than pastor/leadership </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 3,221 </td>
   <td style="text-align:right;"> 2.94 </td>
   <td style="text-align:right;"> 1.38 </td>
   <td style="text-align:right;"> -0.01 </td>
   <td style="text-align:right;"> -1.22 </td>
   <td style="text-align:right;"> 0.75 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ38 - Unrealistic demands placed on my moral/religious behavior </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.16 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 2.95 </td>
   <td style="text-align:right;"> 1.40 </td>
   <td style="text-align:right;"> -0.01 </td>
   <td style="text-align:right;"> -1.26 </td>
   <td style="text-align:right;"> 0.80 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ71 - Avoiding religious activities/settings to reduce distressing feelings </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 0.17 </td>
   <td style="text-align:right;"> 3,074 </td>
   <td style="text-align:right;"> 3.01 </td>
   <td style="text-align:right;"> 1.36 </td>
   <td style="text-align:right;"> -0.06 </td>
   <td style="text-align:right;"> -1.19 </td>
   <td style="text-align:right;"> 0.74 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ69 - Lack of spiritual direction/purpose </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.32 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 3,071 </td>
   <td style="text-align:right;"> 3.01 </td>
   <td style="text-align:right;"> 1.20 </td>
   <td style="text-align:right;"> -0.06 </td>
   <td style="text-align:right;"> -0.83 </td>
   <td style="text-align:right;"> 0.57 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ39 - Made to feel shame over natural sexual desires (not actions) </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.22 </td>
   <td style="text-align:right;"> 3,219 </td>
   <td style="text-align:right;"> 3.05 </td>
   <td style="text-align:right;"> 1.48 </td>
   <td style="text-align:right;"> -0.12 </td>
   <td style="text-align:right;"> -1.37 </td>
   <td style="text-align:right;"> 0.72 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ80 - Feeling isolated </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.29 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.13 </td>
   <td style="text-align:right;"> 3,070 </td>
   <td style="text-align:right;"> 3.07 </td>
   <td style="text-align:right;"> 1.23 </td>
   <td style="text-align:right;"> -0.17 </td>
   <td style="text-align:right;"> -0.91 </td>
   <td style="text-align:right;"> 0.68 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> IQ77 - Anger upon reflecting on negative religious experiences </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.26 </td>
   <td style="text-align:right;"> 0.26 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 3,075 </td>
   <td style="text-align:right;"> 3.08 </td>
   <td style="text-align:right;"> 1.28 </td>
   <td style="text-align:right;"> -0.16 </td>
   <td style="text-align:right;"> -1.02 </td>
   <td style="text-align:right;"> 0.77 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ35 - Taught to distrust my emotions </td>
   <td style="text-align:right;"> 0.19 </td>
   <td style="text-align:right;"> 0.14 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.23 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 3.12 </td>
   <td style="text-align:right;"> 1.39 </td>
   <td style="text-align:right;"> -0.18 </td>
   <td style="text-align:right;"> -1.20 </td>
   <td style="text-align:right;"> 0.74 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ25 - Feeling unable to raise questions and issues </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.25 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 3,217 </td>
   <td style="text-align:right;"> 3.18 </td>
   <td style="text-align:right;"> 1.32 </td>
   <td style="text-align:right;"> -0.26 </td>
   <td style="text-align:right;"> -1.04 </td>
   <td style="text-align:right;"> 0.76 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ66 - Others treated as less than due to their sexual orientation </td>
   <td style="text-align:right;"> 0.18 </td>
   <td style="text-align:right;"> 0.12 </td>
   <td style="text-align:right;"> 0.21 </td>
   <td style="text-align:right;"> 0.25 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 3,216 </td>
   <td style="text-align:right;"> 3.27 </td>
   <td style="text-align:right;"> 1.41 </td>
   <td style="text-align:right;"> -0.34 </td>
   <td style="text-align:right;"> -1.15 </td>
   <td style="text-align:right;"> 0.71 </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left;"> EQ22 - Expected to follow pastor/leader rules re: dating/marriage/sex </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.11 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.24 </td>
   <td style="text-align:right;"> 0.30 </td>
   <td style="text-align:right;"> 3,218 </td>
   <td style="text-align:right;"> 3.33 </td>
   <td style="text-align:right;"> 1.49 </td>
   <td style="text-align:right;"> -0.39 </td>
   <td style="text-align:right;"> -1.28 </td>
   <td style="text-align:right;"> 0.70 </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">

</div>
</section>
<section id="unidimensionality-and-local-independence" class="level2">
<h2 class="anchored" data-anchor-id="unidimensionality-and-local-independence">Unidimensionality and Local Independence</h2>
<section id="principal-components" class="level3">
<h3 class="anchored" data-anchor-id="principal-components">Principal Components</h3>
<p>We first analyzed the principal components in the 59 SHAS items. As shown in <a href="#fig-pca">Figure&nbsp;<span>2</span></a>, the first component was large, accounting for nearly 30% of the variance. The second, third, and fourth components accounted for 4%, 3%, and 2% of the variance, respectively. The ratio of the eigenvalue of the first (largest) component to that of the second is approximately 13.</p>
<div class="cell" data-verbose="false">
<div class="cell-output-display">
<div id="fig-pca" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-pca-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 2: Principal Components</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="proportion-of-variance" class="level3">
<h3 class="anchored" data-anchor-id="proportion-of-variance">Proportion of Variance</h3>
<p>Second, we estimated a unidimensional Rasch model on dichotomized responses to the 59 SHAS items and saved the residuals of the person parameters. We calculated the variance in the observed item responses and the variance of the residuals. <span class="citation" data-cites="Reckase1979">Reckase (<a href="#ref-Reckase1979" role="doc-biblioref">1979</a>)</span> suggests that the unidimensionality assumption is safely met if the Rasch model explains 20% of the variance in the data. In this case, the proportion of variance in the SHAS item data explained by the Rasch model was .23. Thus, the SHAS data meet this criterion.</p>
<div class="cell" data-verbose="false">

</div>
</section>
<section id="principal-component-analysis-of-residuals-pcar" class="level3">
<h3 class="anchored" data-anchor-id="principal-component-analysis-of-residuals-pcar">Principal Component Analysis of Residuals (PCAR)</h3>
<p>Next, we examined the principal components of the correlations among residuals of the Rasch analysis. The premise is that once the Rasch model has been estimated, correlations among the item residuals should be minimal. Linacre () suggests that contrasts with eigenvalues of 2.0 or below can be considered noise. In <a href="#fig-pcar">Figure&nbsp;<span>3</span></a>, our PCAR analysis found only one contrast that rose above that 2.0 threshold.</p>
<div class="cell" data-verbose="false">
<div class="cell-output-display">
<div id="fig-pcar" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-pcar-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 3: Contrasts from PCA of Standardized Residual Correlations</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="q3" class="level3">
<h3 class="anchored" data-anchor-id="q3">Q3</h3>
<p>Finally, we calculated the Q3 statistic <span class="citation" data-cites="Yen1984"><span>“Effects of Local Item Dependence on the Fit and Equating Performance of the Three-Parameter Logistic Model”</span> (<a href="#ref-Yen1984" role="doc-biblioref">1984</a>)</span> to examine correlations among item residuals, the premise being that the latent trait should account for so much common variance in the item responses that any net correlations among the items should be weak. The Q3 statistic index criteria are that the raw residual correlation between pairs of items should never exceed 0.10 (Marais &amp; Andrich, 2008). Of the 1,711 item pairs, the mean correlation was -0.017 with a standard deviation of 0.035. Thus, most of the residual correlations among items were very weak. <a href="#fig-q3">Figure&nbsp;<span>4</span></a> plots the matrix of correlations between item residuals. Each square depicts a correlation. The squares are shaded in grey with the lightest shade indicating the weakest correlations. As hoped, the vast majority of squares are very light, indicating weak correlations among the item residuals.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
WLE Reliability= 0.918 
Yen's Q3 Statistic based on an estimated theta score 
*** 60 Items | 1770 item pairs
*** Q3 Descriptives
     M     SD    Min    10%    25%    50%    75%    90%    Max 
-0.017  0.036 -0.109 -0.055 -0.040 -0.020 -0.001  0.025  0.321 </code></pre>
</div>
<div class="cell-output-display">
<div id="fig-q3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-q3-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 4: Correlation Matrix of Item Residuals</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="rasch-rating-scale-analysis" class="level2">
<h2 class="anchored" data-anchor-id="rasch-rating-scale-analysis">Rasch Rating Scale Analysis</h2>
<p>We used the Rasch Rating Scale Model (RSM) <span class="citation" data-cites="Andrich1978">(<a href="#ref-Andrich1978" role="doc-biblioref">Andrich 1978</a>)</span> to examine the SHAS item pool. The RSM is a Rasch model <span class="citation" data-cites="Rasch1960">(<a href="#ref-Rasch1960" role="doc-biblioref">Rasch 1960</a>)</span> that combines (or “calibrates”) information from items with information from persons to arrive at a common scale for measuring both an item’s and a person’s level of a latent trait, in this case, severity of spiritual abuse. This scale is expressed in logits (log odds units). Whereas the Rasch model was designed for use with dichotomous items (0 = incorrect response, 1 = correct response), the RSM is an extension for use with polytomous items based on rating scales such as Likert scales of agreement <span class="citation" data-cites="EmbretsonReise2000">(<a href="#ref-EmbretsonReise2000" role="doc-biblioref">Embretson and Reise 2000</a>)</span>.</p>
<p>We also use different language from conventional IRT analyses. Because IRT was developed to measure student achievement, IRT statistics for both items and persons tend to use language of “ability” and “difficulty.” For our purpose to measure a psychological trait such as the experience of spiritual abuse, we chose instead to adopt language of “severity.” We used person parameters and scale scores to represent participants’ severity of abuse and to describe item parameters as severity parameters.</p>
<p>library(tidyverse) library(dplyr) library(tidyr) library(knitr) library(kableExtra) library(stats4) library(lattice) library(mirt) library(WrightMap)</p>
<p>The RSM estimates the probability of a person choosing among several response options (i.e.&nbsp;Never, Once or twice) given two values: the severity of abuse represented by the item, and the person’s severity of the latent trait (spiritual abuse). The increase in severity involved in choosing between two response categories is called a “step parameter”. The RSM makes two assumptions of the response categories. One is that all items use the same rating scale. The other is that the same response categories distinguish persons equally well for each item. For these reasons the RSM estimates the same step parameters for all the items.</p>
<p>To convey this information visually, <a href="#fig-RM-plot1">Figure&nbsp;<span>5</span></a> and <a href="#fig-RM-plot2">Figure&nbsp;<span>6</span></a> are plots of the category response functions of two items. In both, the horizontal axis is the scale of spiritual abuse expressed in logits ranging from -2 to +2. The vertical axis is the probability of selecting a given response (i.e., “Always”) given the person’s overall severity of spiritual abuse. The blue line is the probability of selecting Category 1 (“Never”) for persons with less severe spiritual abuse. Persons with less severe spiritual abuse are most likely to select “Never” while those with more severe abuse are most likely to select “Always.” Between these two extremes are persons with more moderate or average spiritual abuse. These persons are more likely to Categories 3 or 4, “Sometimes” or “Often”, respectively. Both plots show curves that display identical step parameters.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Iteration in WLE/MLE estimation  1   | Maximal change  2.7551 
Iteration in WLE/MLE estimation  2   | Maximal change  0.8593 
Iteration in WLE/MLE estimation  3   | Maximal change  0.4864 
Iteration in WLE/MLE estimation  4   | Maximal change  0.1926 
Iteration in WLE/MLE estimation  5   | Maximal change  0.028 
Iteration in WLE/MLE estimation  6   | Maximal change  0.0012 
Iteration in WLE/MLE estimation  7   | Maximal change  0 
----
 WLE Reliability= 0.963 </code></pre>
</div>
<div class="cell-output-display">
<div id="fig-RM-plot1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-RM-plot1-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 5: Category Response Plots</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Iteration in WLE/MLE estimation  1   | Maximal change  2.7551 
Iteration in WLE/MLE estimation  2   | Maximal change  0.8593 
Iteration in WLE/MLE estimation  3   | Maximal change  0.4864 
Iteration in WLE/MLE estimation  4   | Maximal change  0.1926 
Iteration in WLE/MLE estimation  5   | Maximal change  0.028 
Iteration in WLE/MLE estimation  6   | Maximal change  0.0012 
Iteration in WLE/MLE estimation  7   | Maximal change  0 
----
 WLE Reliability= 0.963 </code></pre>
</div>
<div class="cell-output-display">
<div id="fig-RM-plot2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-RM-plot2-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 6: Category Response Plots</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>These plots point out a step reversal between “Never” and “Once or twice”. Persons reporting the least severe spiritual abuse were most likely to report “Never” to this prompt of medical care being postponed or withheld for religious reasons. Persons farther along the scale who have experienced “average” average spiritual abuse should be more likely to report “Once or twice” but were still more likely to report “Never”. This finding suggests the “Never” and “Once or twice” categories might be collapsed.</p>
<section id="item-severity-parameters-and-fit-statistics" class="level3">
<h3 class="anchored" data-anchor-id="item-severity-parameters-and-fit-statistics">Item Severity Parameters and Fit Statistics</h3>
<p><a href="#tbl-RSM-item-tbl">Table&nbsp;<span>4</span></a> reports item parameters and fit statistics for the SHAS items. The first column, xsi, reports the severity parameter of the item, and we have sorted the items by this value from least to most severe to facilitate comparison between items. <a href="#tbl-RSM-item-tbl">Table&nbsp;<span>4</span></a> also reports fit statistics for the items. These statistics reflect how closely the observed patterns of item responses fit the patterns of item responses predicted by the RSM. These fit statistics are chi-square statistics which examine the cumulative difference the observed pattern of item responses and the pattern of item responses that the model would expect.</p>
<p>Two fit statistics commonly used in IRT models are the infit mean square and the outfit mean square <span class="citation" data-cites="BondFox2015">(<a href="#ref-BondFox2015" role="doc-biblioref">Bond and Fox 2015</a>)</span>. The infit statistic places greater emphasis on unexpected responses that are close to the persons and item location. The outfit is sensitive to unexpected responses that are far from the location. The expected value of infit or outfit for each item is 1.0, with a range of acceptable values ranging from 0.5 to 1.5. Values outside these boundaries indicate a lack of fit between items and the model. All but one of the 60 items had infit and outfit statistics within the acceptable range.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-RSM-item-tbl" class="anchored">

<table class="table" style="margin-left: auto; margin-right: auto;"><caption>Table 4:  Estimated Item Parameters for the Rating Scale Model and Item Chi-Square Fit Statistics </caption>
 <thead>
<tr>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="2"></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Item Parameters</div></th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="2"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">Fit Statistics</div></th>
</tr>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:center;"> subscale </th>
   <th style="text-align:center;"> xsi </th>
   <th style="text-align:center;"> se.xsi </th>
   <th style="text-align:center;"> Outfit </th>
   <th style="text-align:center;"> Infit </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ22 - Expected to follow pastor/leader rules re: dating/marriage/sex </td>
   <td style="text-align:center;"> controlling leadership </td>
   <td style="text-align:center;"> -0.42 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.21 </td>
   <td style="text-align:center;"> 1.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ66 - Others treated as less than due to their sexual orientation </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> -0.35 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.10 </td>
   <td style="text-align:center;"> 1.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ25 - Feeling unable to raise questions and issues </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> -0.26 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.77 </td>
   <td style="text-align:center;"> 0.76 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ35 - Taught to distrust my emotions </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> -0.19 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.06 </td>
   <td style="text-align:center;"> 0.97 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ77 - Anger upon reflecting on negative religious experiences </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> -0.13 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.71 </td>
   <td style="text-align:center;"> 0.69 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ39 - Made to feel shame over natural sexual desires (not actions) </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> -0.12 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.12 </td>
   <td style="text-align:center;"> 1.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ80 - Feeling isolated </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> -0.11 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.93 </td>
   <td style="text-align:center;"> 0.86 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ69 - Lack of spiritual direction/purpose </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> -0.05 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.36 </td>
   <td style="text-align:center;"> 1.12 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ71 - Avoiding religious activities/settings to reduce distressing feelings </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> -0.04 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.93 </td>
   <td style="text-align:center;"> 0.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ38 - Unrealistic demands placed on my moral/religious behavior </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.00 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.75 </td>
   <td style="text-align:center;"> 0.78 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ37 - Made to feel less spiritually mature than pastor/leadership </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.01 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.92 </td>
   <td style="text-align:center;"> 0.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ54 - Being explicitly taught to distrust my intuitions </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.03 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.94 </td>
   <td style="text-align:center;"> 0.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> IQ76 - Feeling I wasted years of my life in a church/set of beliefs </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.15 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.06 </td>
   <td style="text-align:center;"> 1.09 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ32 - Feeling unable to express unhappiness </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.17 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.91 </td>
   <td style="text-align:center;"> 0.88 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ61 - Developmentally-inappropriate/anxious end times descriptions taught to young children </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.10 </td>
   <td style="text-align:center;"> 1.14 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ36 - Mental/physical problems interpreted as spiritual/moral weakness </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.18 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.82 </td>
   <td style="text-align:center;"> 0.82 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ74 - Sadness over the loss of my faith/religious community </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> 0.19 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.33 </td>
   <td style="text-align:center;"> 1.18 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ45 - Developmentally-inappropriate/anxious Hell/Satan/demons taught to young children </td>
   <td style="text-align:center;"> spiritual violence </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.09 </td>
   <td style="text-align:center;"> 1.11 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ78 - A lack of self-worth </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> 0.20 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.09 </td>
   <td style="text-align:center;"> 1.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ18 - Church/pastor discourage critical thinking </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.22 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.82 </td>
   <td style="text-align:center;"> 0.84 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ56 - Being made to feel I was crazy/weird for doubts/questions </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.24 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.68 </td>
   <td style="text-align:center;"> 0.71 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ44 - Love/acceptance offered only for high spiritual/moral performance </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.36 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.76 </td>
   <td style="text-align:center;"> 0.75 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ42 - Seeing others shamed/shunned by pastor/leader/group </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.38 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.75 </td>
   <td style="text-align:center;"> 0.73 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ7 - Pastor speaking on God's behalf </td>
   <td style="text-align:center;"> controlling leadership </td>
   <td style="text-align:center;"> 0.45 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.36 </td>
   <td style="text-align:center;"> 1.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ58 - Terror/horror used to motivate religious decisions </td>
   <td style="text-align:center;"> spiritual violence </td>
   <td style="text-align:center;"> 0.45 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.92 </td>
   <td style="text-align:center;"> 0.95 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ11 - Disagree w/pastor portrayed as evil </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.47 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.84 </td>
   <td style="text-align:center;"> 0.86 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ73 - Self-hatred or self-loathing </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> 0.51 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.18 </td>
   <td style="text-align:center;"> 1.16 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ29 - Feeling special when in pastor’s good graces; otherwise ignored </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.52 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.12 </td>
   <td style="text-align:center;"> 1.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ34 - Scripture used to justify physical punishment/severe discipline </td>
   <td style="text-align:center;"> spiritual violence </td>
   <td style="text-align:center;"> 0.53 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.21 </td>
   <td style="text-align:center;"> 1.17 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ79 - Distrust of God </td>
   <td style="text-align:center;"> harmful God-image </td>
   <td style="text-align:center;"> 0.62 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.34 </td>
   <td style="text-align:center;"> 1.20 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ53 - Scripture used to justify abusive parent-child behavior </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.64 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.95 </td>
   <td style="text-align:center;"> 1.01 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ51 - Extreme pressure to be pastor/missionary/spiritual leader </td>
   <td style="text-align:center;"> controlling leadership </td>
   <td style="text-align:center;"> 0.67 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.40 </td>
   <td style="text-align:center;"> 1.38 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ19 - Behavior excessively monitored by pastor/group </td>
   <td style="text-align:center;"> controlling leadership </td>
   <td style="text-align:center;"> 0.69 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.86 </td>
   <td style="text-align:center;"> 0.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ63 - Shamed by pastor/group for raising questions or concerns </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.72 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.76 </td>
   <td style="text-align:center;"> 0.78 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ40 - Threatening Divine punishment to keep group members in line </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.74 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.93 </td>
   <td style="text-align:center;"> 1.02 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ28 - Leadershi/group protecting abusive individuals </td>
   <td style="text-align:center;"> maintain system </td>
   <td style="text-align:center;"> 0.76 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.92 </td>
   <td style="text-align:center;"> 0.90 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ64 - Witnessing women pressured to stay in unfaithful/abusive marriages </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.77 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.00 </td>
   <td style="text-align:center;"> 0.99 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ50 - Treated as less than because of my gender </td>
   <td style="text-align:center;"> gender discrimination </td>
   <td style="text-align:center;"> 0.79 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.96 </td>
   <td style="text-align:center;"> 1.92 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ82 - Having trouble navigating life outside my church/community </td>
   <td style="text-align:center;"> internal distress </td>
   <td style="text-align:center;"> 0.80 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.16 </td>
   <td style="text-align:center;"> 1.15 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ21 - Taught I would risk Hell if left my church/group </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.83 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.32 </td>
   <td style="text-align:center;"> 1.39 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ59 - Pastor/group blame victim for their abuse </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.87 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.76 </td>
   <td style="text-align:center;"> 0.81 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ62 - Scripture used to justify physical violence </td>
   <td style="text-align:center;"> spiritual violence </td>
   <td style="text-align:center;"> 0.88 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.07 </td>
   <td style="text-align:center;"> 1.11 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ20 - Members pressured to give money despite financial hardship </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.88 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.14 </td>
   <td style="text-align:center;"> 1.27 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ57 - Developing mental/physical ailments from conforming to group/leader’s expectation </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.89 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.94 </td>
   <td style="text-align:center;"> 1.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ16 - Church/community abandoning me in difficult time </td>
   <td style="text-align:center;"> maintain system </td>
   <td style="text-align:center;"> 0.92 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.02 </td>
   <td style="text-align:center;"> 1.05 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ49 - Leadership/group protecting and elevating abusive individuals </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 0.92 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.89 </td>
   <td style="text-align:center;"> 0.93 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ70 - Feeling betrayed by God </td>
   <td style="text-align:center;"> harmful God-image </td>
   <td style="text-align:center;"> 0.95 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.38 </td>
   <td style="text-align:center;"> 1.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ52 - Blamed for harm I suffered rather than blaming who harmed me </td>
   <td style="text-align:center;"> maintain system </td>
   <td style="text-align:center;"> 0.98 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.80 </td>
   <td style="text-align:center;"> 0.89 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> IQ68 - Anxiety attacks triggered by religious stimuli </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.03 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.99 </td>
   <td style="text-align:center;"> 1.07 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ30 - Deterred from seeking mental health treatment/counseling/medication </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.03 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.95 </td>
   <td style="text-align:center;"> 1.03 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ43 - Shamed by pastor/group for poor spiritual/moral performance </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.03 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.82 </td>
   <td style="text-align:center;"> 0.84 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ31 - Shunned/ignored by pastor/church/group </td>
   <td style="text-align:center;"> maintain system </td>
   <td style="text-align:center;"> 1.04 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.13 </td>
   <td style="text-align:center;"> 1.09 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ23 - Prayer replacing needed medical interventions </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.19 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.07 </td>
   <td style="text-align:center;"> 1.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ24 - Expected to consult pastor/leader before making non-religious decisions </td>
   <td style="text-align:center;"> controlling leadership </td>
   <td style="text-align:center;"> 1.24 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.02 </td>
   <td style="text-align:center;"> 1.08 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *EQ26 - Pressured to forgive abuser while abuse was ongoing </td>
   <td style="text-align:center;"> maintain system </td>
   <td style="text-align:center;"> 1.26 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.34 </td>
   <td style="text-align:center;"> 1.30 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ10 - Asked to give up personal goals by pastor </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.32 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.11 </td>
   <td style="text-align:center;"> 1.19 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ65 - Cut off/shunned by more religious family members </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.33 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.28 </td>
   <td style="text-align:center;"> 1.26 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> IQ81 - Nightmares about my negative religious experiences </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.42 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 0.89 </td>
   <td style="text-align:center;"> 0.96 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> *IQ72 - Feeling as if God harmed me directly </td>
   <td style="text-align:center;"> harmful God-image </td>
   <td style="text-align:center;"> 1.64 </td>
   <td style="text-align:center;"> 0.02 </td>
   <td style="text-align:center;"> 1.14 </td>
   <td style="text-align:center;"> 1.22 </td>
  </tr>
  <tr>
   <td style="text-align:left;width: 11cm; "> EQ47 - Medical care being postponed/withheld for religious reasons </td>
   <td style="text-align:center;">  </td>
   <td style="text-align:center;"> 1.94 </td>
   <td style="text-align:center;"> 0.03 </td>
   <td style="text-align:center;"> 1.12 </td>
   <td style="text-align:center;"> 1.16 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-RSM-item-histogram" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-RSM-item-histogram-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 7: Distribution of Item Severity Parameters</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="reliability" class="level3">
<h3 class="anchored" data-anchor-id="reliability">Reliability</h3>
<p>The RSM expresses internal consistency reliability as Rasch person separation. Based on Table X, the SHAS has a high Rasch person separation reliability value of .963, indicating that the estimated RSM scale discriminated well between persons with varying severity of spiritual abuse.</p>
<p>The SHAS also has a high Rasch item separation reliability with Rel = .XX, χ2 (XX) = XXXX.X, p &lt; .XX, implying that the items have a good spread in terms of item ordering and hierarchy.</p>
<div class="cell">

</div>
</section>
<section id="item-person-map" class="level3">
<h3 class="anchored" data-anchor-id="item-person-map">Item-Person Map</h3>
<p><a href="#fig-RSM-WrightMap">Figure&nbsp;<span>8</span></a> displays an item-person map (also called a “Wright map”) that shows the item severities of the SHAS items and the person severities for each person who completed the survey. All these severities are estimated in logits (log odds units) as the unit of measures. This means the higher the logit value for an item is, the less likely it was for a person to endorse that particular item. On the other hand, higher logit values for each person indicate more severe spiritual abuse. On the variable map, the mean item severity is constrained to be 0.00 with person severities being relative to that mean item severity While column 1 shows the latent continuum in terms of logit values as the unit of measurement underlying the SHAS, columns 2 and 3 represent the severities of the people and the items.</p>
<p><a href="#fig-RSM-WrightMap">Figure&nbsp;<span>8</span></a> shows good overlap between the person trait and item severity as evidenced by the match between the mean of the person severity (M = − 0.58) and the mean of the item severity (M = 0.00). This suggests that the majority of the items were appropriate for the sample. While person severity measures range from X.XX logits to − X.XX logits (M = − 0.XX, SD = 0.XX, N = XXXX), the item severities range from X.XX logits to − X.XX logits (M = X.XX, SD = 0.XX, N = XXXX). The item representing the most severe spiritual abuse for participants is Item X, “I feel … XXX” with the severity at X.XX logits (also reported in Appendix Table 2). By contrast the item representing the least severe spiritual abuse is item XX, “I would …”, with − 1.08 logits.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-RSM-WrightMap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="results_files/figure-html/fig-RSM-WrightMap-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Figure 8: Item-Person Map</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-data-fit" class="level3">
<h3 class="anchored" data-anchor-id="model-data-fit">Model-Data Fit</h3>
<p>To assess the overall fit of the RSM to the SHAS item response data, we use two statistics. The first is the Root Mean Square Error of Approximation (RMSEA). The suggested cutoff for RMSEA is .06. The second is the CFI. The suggested cutoff for the CFI is .95. These fit statistics are presented in Table RSM Model Fit.</p>
<div class="cell" data-tbl-cap="RSM Model Fit">
<div class="cell-output cell-output-stdout">
<pre><code>'log Lik.' -225573.6 (df=64)</code></pre>
</div>
</div>
<p>The obtained RMSEA value of .09 (95% CI[.092, .093]) exceeds the cutoff of .06. The CFI of .953 meets the recommended .95 threshold. Together these statistics evidence that the RSM fits the SHAS items.</p>
</section>
</section>
<section id="dif-analysis" class="level2">
<h2 class="anchored" data-anchor-id="dif-analysis">DIF Analysis</h2>
<p>Differential item functioning (DIF) examines how an item functions differently for people of equal standing on the trait. In this case, we conducted DIF analysis of the SHAS items to examine item bias by gender, and age, and race. [We applied logistic ordinal regression with IRT scoring. [We used the Chi-squared likelihood-ratio statistic as the initial DIF detection criteria (alpha &lt; 0.01) and a cut-off of McFadden pseudo R2Δ ≥ 0.02 in model comparisons to determine substantial DIF, a reasonable threshold used in the development of self-reported health outcomes.]</p>
<div class="cell" data-verbose="false">

</div>
<p>In this analysis, we examined the degree to which there was evidence of uniform differential item functioning (DIF) between two subgroups of participants (group 1 and group 2). As a first step we examined item severity estimates and standard errors specific to each subgroup using the Rating Scale Model <span class="citation" data-cites="Andrich1978">Andrich (<a href="#ref-Andrich1978" role="doc-biblioref">1978</a>)</span>. We estimated item severity for the two subgroups using a combined analysis of both subgroups and then estimating the group-specific item severities and standard errors are shown in Table X.</p>
<p>To examine the differences in item severity between subgroups, we calculated standardized differences following Wright and Masters (1982) as follows:</p>
<p>[equation]</p>
<p>where<br>
z is the standardized difference, d1 is the item severity specific to Subgroup 1, d2 is the item severity specific to Subgroup 2,<br>
s e 2 1 is the standard error of the item severity specific to Subgroup 1, and<br>
s e 2 2 is the standard error of the item severity specific to Subgroup 2. Using the formulation of the z statistic, higher values of z indicate higher item locations (more-severe to endorse) for Subgroup 1 compared to Subgroup 2.</p>
<p>Figure X shows a plot of the z-statistics for the four items; these values are also presented numerically in Table X. In the figure, the x-axis shows the item identification numbers, and the y-axis shows the value of the z-statistic. Boundaries at +2 and -2 are indicated using dashed horizontal lines to highlight statistically significant differences in item severity between subgroups. Examination of these results indicates that the items were not significantly different in severity between the two subgroups. In addition, there were both positive and negative z statistics, indicating that although the differences in item severity were not significant, there were some items that were easier to endorse for Subgroup 1 and others that were easier to endorse for Subgroup 2.</p>
<p>Figure 1: Plot of Standardized Differences for Items between Subgroups</p>
<p>To further explore the differences in item severity between the two subgroups, Figure 2 shows a scatterplot of the item locations between the two subgroups. In the plot, the item severity for Subgroup 1 is shown on the x-axis, and the item severity for Subgroup 2 is shown on the y-axis. Individual items are indicated using open circle plotting symbols. A solid identity line is included to highlight deviations from invariant item severities between the two groups: Points that fall below this line indicate that items were easier to endorse (lower item measures) for Subgroup 2, and points that fall above the line indicate that items were easier to endorse (lower item measures) for Subgroup 1. Dashed lines are also included to indicate a 95% confidence interval for the difference between the item measures, following Luppescu (1995).</p>
<p>Figure 2: Scatterplot of Subgroup-Specific Item Severities</p>
<p>Finally, Figure 3 is a bar plot that illustrates the direction and magnitude of the differences in item severities between subgroups. In the plot, each bar represents the difference in severity between subgroups for an individual item, ordered by the item sequence in the survey. Bars that point to the left of the plot indicate that the item was easier to endorse for Subgroup 1, and bars that point to the right of the plot indicate that the item was easier to endorse for Subgroup 2. Dashed vertical lines are plotted that show values of +0.5 and -0.5 logits as an indicator of substantial differences in item severity between subgroups.</p>
<p>Figure 3: Bar Plot of Differences In Item Severity Between Subgroups</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Andrich1978" class="csl-entry" role="doc-biblioentry">
Andrich, David. 1978. <span>“A Rating Formulation for Ordered Response Categories.”</span> <em>Psychometrika</em> 43: 561–73.
</div>
<div id="ref-BondFox2015" class="csl-entry" role="doc-biblioentry">
Bond, Trevor G., and Christine M. Fox. 2015. <em>Applying the Rasch Model: Fundamental Measurement in the Human Sciences</em>. New York, New York: Routledge.
</div>
<div id="ref-Yen1984" class="csl-entry" role="doc-biblioentry">
<span>“Effects of Local Item Dependence on the Fit and Equating Performance of the Three-Parameter Logistic Model.”</span> 1984. <em>Applied Psychological Measurement</em> 8 (2): 125–45.
</div>
<div id="ref-EmbretsonReise2000" class="csl-entry" role="doc-biblioentry">
Embretson, Susan E., and Steven P. Reise. 2000. <em>Item Response Theory for Psychologists</em>. Mahwah, New Jerey: Lawrence Erlbaum Associates.
</div>
<div id="ref-Rasch1960" class="csl-entry" role="doc-biblioentry">
Rasch, Georg. 1960. <em>Probabilistic Models for Some Intelligence and Attainment Tests</em>. Chicago, IL: University of Chicago Press.
</div>
<div id="ref-Reckase1979" class="csl-entry" role="doc-biblioentry">
Reckase, Mark D. 1979. <span>“Unifactor Latent Trait Models Applied to Multifactor Tests: Results and Implications.”</span> <em>Journal of Educational Statistics</em> 4: 207–30.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./methods.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Methods</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./discussion.html" class="pagination-link">
        <span class="nav-page-text">Discussion</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>