### IRT Model Assumptions

IRT models make two assumptions of the data. The first is unidimensionality of the data. This is the assumption that "a single common latent variable accounts for all the common variance among the items" [@ReiseEtAl2013].  The SHAS items were multidimensional by design. The construct of spiritual harm and abuse is not conceptually narrow, and Dan wrote two distinct sets of items -- external events and internal states -- to cover the breadth of this construct. The exploratory factor analyses found a handful of factors in the SHAS items. A unidimensional IRT model can be fit to multidimensional data [@ReiseEtAl2013]. We need evidence of a strong common trait.

The second assumption is local independence [@EmbretsonReise2000]. This means that, once the latent variable has been accounted for, any set of items should not share any meaningful correlation (Edwards, Houts, & Cai, 2018).

Following @ReiseEtAl2013, we conducted several analyses: (a) inspection of eigenvalues from principal component or factor analysis (e.g., how large is the ratio of the first to second eigenvalue?), (b) determining dimensionality through parallel analysis, (c) compared the fit of a one-factor confirmatory model against benchmarks (e.g., comparative fit index > .90), and (d) inspected residuals after fitting a unidimensional IRT model. First we confirmed the factor structure using confirmatory factor analysis (CFA). Then we determined the proportion of variance in the observed item responses due to the Rasch model. Finally, we conducted Rasch Principal Component Analysis of Residuals (PCAR) (Smith, 2002).

